adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    # path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    # path('categories/read/', adminapp.categories, name='categories'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp.views import index, contacts

# import mainapp.views as mainapp - можно сразу все импортнуть


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    # path('contacts/', mainapp.contacts, name='contacts'), - если все импортировали, то подгружать так
    path('products/', include('productsapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('get/price/<int:pk>/', ordersapp.get_item_price, name='get_item_price'),
    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),

]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.shortcuts import render

from productsapp.models import Product
from productsapp.views import get_products


def index(request):
    title = 'главная'
    # products = Product.objects.filter(is_active=True, category__is_active=True)[:3]
    products = get_products()[:3]

    context = {
        'title': title,
        'products': products,
    }
    return render(request, 'mainapp/index.html', context=context)


def contacts(request):
    title = 'контакты'

    context = {
        'title': title,
    }
    return render(request, 'mainapp/contacts.html', context=context)

mainapp/templates/mainapp/includes/inc_mainmenu.html
<a href="{% url 'index' %}" class="logo"></a>

<ul class="menu">
	<li><a href="{% url 'index' %}" class="{% if request.resolver_match.route == '' %}active{% endif %}">домой</a></li>
	<li><a href="{% url 'products:index' %}" class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">продукты</a></li>
	<li><a href="{% url 'contacts' %}" class="{% if request.resolver_match.route == 'contacts/' %}active{% endif %}">контакты</a></li>
    {% if user.is_authenticated %}
    <li>
        <div class="dropdown">
            <a href="#">{{ user.first_name|default:'Аноним' }}</a>
            <div class="dropdown-content">
                <a href="{% url 'auth:edit' %}">профиль</a>
                <a href="{% url 'ordersapp:orders_list' %}">заказы</a>
                {% if user.is_superuser %}
                    <a href="{% url 'admin_staff:users' %}">админка</a>
                {% endif %}
            </div>
        </div>
    </li>
    {% endif %}
{% if basket %}
    <li>
        <div class="dropdown">
            <a href="{% url 'basket:index' %}" class="basket_"><i class="fa fa-cart-plus" aria-hidden="true"></i></a>
            <div class="dropdown-content">
                <a href="{% url 'basket:index' %}">кол-во {{ basket.0.total_quantity }}</a>
                <a href="{% url 'basket:index' %}">стоимость {{ basket.0.total_cost|floatformat:0 }}р.</a>
            </div>
        </div>
    </li>
{% endif %}
     <li>
    {% if user.is_authenticated %}
      <a href="{% url 'auth:logout' %}" title="выйти"><i class="fas fa-sign-out-alt"></i></a>
    {% else %}
      <a href="{% url 'auth:login' %}" title="войти"><i class="fas fa-sign-in-alt"></i></a>
    {% endif %}
    </li>
</ul>




<!-- a href="#" class="search"></a -->