adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    # path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    # path('categories/read/', adminapp.categories, name='categories'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp.views import index, contacts

# import mainapp.views as mainapp - можно сразу все импортнуть


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    # path('contacts/', mainapp.contacts, name='contacts'), - если все импортировали, то подгружать так
    path('products/', include('productsapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

products/urls.py
from django.urls import path, include
# from .views import products
import products.views as products

urlpatterns = [
    # path('', products),
    path('', products.index),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from productsapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    # Виртуальное поле, его нет в БД. Не сохраняется в БД (required) и задаем имя (label)
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        # fields = '__all__'
        exclude = ()


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'description' and field.widget.input_type == 'checkbox':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'description' and field.widget.input_type == 'checkbox':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.db.models import F
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from authapp.forms import ShopUserRegisterForm
from productsapp.models import Product, ProductCategory
from authapp.models import ShopUser

from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection


# вывод в терминал sql запроса
def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


# Эффективное обновление атрибута нескольких объектов при помощи «.update()» - массовый sql запрос
# При скрытии категории, скрываются все позиции товаров
@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)


class UsersListView(ListView):
    model = ShopUser
    queryset = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
    template_name = 'adminapp/users.html'
    extra_context = {'title': 'админка/пользователи'}
    paginate_by = 6

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка/пользователи'
#
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#
#     content = {
#         'title': title,
#         'objects': users_list
#     }
#
#     return render(request, 'adminapp/users.html', content)


class UserCreateView(CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/user_update.html'
    extra_context = {'title': 'пользователи/создание'}
    success_url = reverse_lazy('admin_staff:users')

    # fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def user_create(request):
#     title = 'пользователи/создание'
#
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users'))
#     else:
#         user_form = ShopUserRegisterForm()
#
#     content = {'title': title, 'update_form': user_form}
#
#     return render(request, 'adminapp/user_update.html', content)

class UserUpdateView(UpdateView):
    model = ShopUser
    form_class = ShopUserAdminEditForm
    template_name = 'adminapp/user_update.html'
    extra_context = {'title': 'пользователи/редактирование'}

    # success_url = reverse_lazy('admin_staff:users')
    # fields = '__all__'

    # если нужно достать pk и передать его в success_url
    def get_success_url(self):
        print(self.object.pk)
        return reverse_lazy('admin_staff:user_update', kwargs={'pk': self.object.pk})

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def user_update(request, pk):
#     title = 'пользователи/редактирование'
#
#     edit_user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:user_update', args=[edit_user.pk]))
#     else:
#         edit_form = ShopUserAdminEditForm(instance=edit_user)
#
#     content = {'title': title, 'update_form': edit_form}
#
#     return render(request, 'adminapp/user_update.html', content)

class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    context_object_name = 'user_to_delete'
    success_url = reverse_lazy('admin_staff:users')
    extra_context = {'title': 'пользователи/удаление'}

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


# @user_passes_test(lambda u: u.is_superuser)
# def user_delete(request, pk):
#     title = 'пользователи/удаление'
#
#     user = get_object_or_404(ShopUser, pk=pk)
#
#     if request.method == 'POST':
#         # user.delete() могли бы сделать
#         # НО вместо удаления лучше сделаем неактивным
#         user.is_active = False
#         user.save()
#         return HttpResponseRedirect(reverse('admin_staff:users'))
#
#     content = {'title': title, 'user_to_delete': user}
#
#     return render(request, 'adminapp/user_delete.html', content)


class ProductCategoryListView(ListView):
    model = ProductCategory
    # queryset = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
    context_object_name = 'objects'
    template_name = 'adminapp/categories.html'
    extra_context = {'title': 'админка/категории'}

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def categories(request):
#     title = 'админка/категории'
#
#     categories_list = ProductCategory.objects.all()
#
#     content = {
#         'title': title,
#         'objects': categories_list
#     }
#
#     return render(request, 'adminapp/categories.html', content)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')

    # fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/создание'

        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     title = 'категории/создание'
#
#     if request.method == 'POST':
#         category_form = ProductCategoryEditForm(request.POST)
#         if category_form.is_valid():
#             category_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:categories'))
#     else:
#         category_form = ProductCategoryEditForm()
#
#     content = {'title': title, 'update_form': category_form}
#
#     return render(request, 'adminapp/category_update.html', content)


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')

    # fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)
        return super().form_valid(form)

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = 'категории/редактирование'
#
#     edit_category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         edit_form = ProductCategoryEditForm(request.POST, instance=edit_category)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:categories'))
#             # return HttpResponseRedirect(reverse('admin_staff:category_update', args=[edit_category.pk]))
#     else:
#         edit_form = ProductCategoryEditForm(instance=edit_category)
#
#     content = {'title': title, 'update_form': edit_form}
#
#     return render(request, 'adminapp/category_update.html', content)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_staff:categories')
    extra_context = {'title': 'категории/удаление'}

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     title = 'категории/удаление'
#
#     category = get_object_or_404(ProductCategory, pk=pk)
#

products/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'products/products.html')

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории товаров</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Товары в категории</th>
                            <th>Редактировать </th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Товары в категории</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for object in objects %}
                            <tr {% if not object.is_active %} style="opacity: 0.5; text-decoration: line-through;" {% endif %}>
                                <td>{{ object.name }}</td>
                                <td class="text-center">
                                    <a href="{% url 'admin_staff:products' object.pk %}"><i class='bx bx-info-circle' ></i></a>
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'admin_staff:category_update' object.pk %}"><i class='bx bxs-edit-alt'></i></a>
                                </td>
                                <td class="text-center">
                                    <a {% if not object.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:category_delete' pk=object.pk %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:category_create'%}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="category_delete">
        Уверены, что хотите удалить <b>{{ product_to_delete.name }}</b>
        {% if product_to_delete.short_desc %}
            ({{ product_to_delete.short_desc }})
        {% endif %}
        ?
        <form action="{% url 'admin_staff:product_delete' product_to_delete.pk %}"
              method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>

        <br>
        <a href="{% url 'admin_staff:products' product_to_delete.category.pk %}">
            <button class="btn btn-success">
                Отмена
            </button>
        </a>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}

    <div class="card" style="width: 18rem;">

        <img src="{{ object.image|media_folder_products }}" class="card-img-top" alt="{{ object.name }}">

        <div class="card-body">
            <h5 class="card-title">{{ object.name|title  }}</h5>
            <p class="card-text">{{ object.short_desc }}</p>
            <p class="card-text text-muted">{{ object.description }}</p>
        </div>
        <div class="card-header"><b>Категория:</b> {{ object.category.name|title }}</div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Цена:</b> {{ object.price }} <i class="fas fa-ruble-sign"></i></li>
            <li class="list-group-item">Количество: {{ object.quantity }} шт.</li>
            <li class="list-group-item">{% if object.is_active %}В каталоге{% else %}Выключена{% endif %}</li>
        </ul>
        <div class="card-body">
            <a href="{% url 'admin_staff:product_update' object.pk %}" class="card-link">редактировать</a>
            <a href="{% url 'admin_staff:product_delete' object.pk %}" class="card-link">удалить</a>
        </div>
        <div class="card-footer"><a href="{% url 'admin_staff:products' object.category.pk %}" class="card-link">назад</a></div>
    </div>


{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Товары в категории {{ category.name }}</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Категории
                </div>
                <div class="card-body">
                    {% if is_paginated %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-end">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{% url 'admin_staff:products' category.pk %}?page={{ page_obj.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                                <li class="page-item"><a class="page-link" href="#">страница {{ page_obj.number }}
                                    из {{ page_obj.paginator.num_pages }}</a></li>
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{% url 'admin_staff:products' category.pk %}?page={{ page_obj.next_page_number }}"
                                           aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Наименование</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Подробнее</th>
                                <th>Редактировать</th>
                                <th>Удалить</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Наименование</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Подробнее</th>
                                <th>Редактировать</th>
                                <th>Удалить</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for object in objects %}
                                <tr {% if not object.is_active %} style="opacity: 0.5;" {% endif %}>
                                    <td>{{ object.name }}</td>
                                    <td>{{ object.price }} <i class="fas fa-ruble-sign"></i></td>
                                    <td>{{ object.quantity }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'admin_staff:product_read' object.pk %}"><i
                                                class='bx bx-info-circle'></i></a>
                                    </td>
                                    <td class="text-center">
                                        <a href="{% url 'admin_staff:product_update' object.pk %}"><i
                                                class='bx bxs-edit-alt'></i></a>
                                    </td>
                                    <td class="text-center">
                                        <a {% if not object.is_active %} class="invisible" {% endif %}
                                                                         href="{% url 'admin_staff:product_delete' pk=object.pk %}">
                                            <i class="fa fa-times-circle"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admin_staff:product_create' category.pk %}">
                        <button class="btn btn-success">Добавить товар в категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Пользователи</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Пользователи
                </div>


                <div class="card-body">
                    {% if is_paginated %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-end">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="{% url 'admin_staff:users' %}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                                <li class="page-item"><a class="page-link" href="#">страница {{ page_obj.number }}
                                    из {{ page_obj.paginator.num_pages }}</a></li>
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="{% url 'admin_staff:users' %}?page={{ page_obj.next_page_number }}"
                                           aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                                <th>Вход</th>
                                <th>Удалить</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                                <th>Вход</th>
                                <th>Удалить</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for object in object_list %}
                                <tr {% if not object.is_active %}
                                    style="opacity: 0.5; text-decoration: line-through;" {% endif %}>
                                    <td><a href="{% url 'admin_staff:user_update' object.id %}"
                                           style="color: dodgerblue">{{ object.username }}</a></td>
                                    <td>{{ object.first_name }}</td>
                                    <td>{{ object.last_name }}</td>
                                    <td>{{ object.email }}</td>
                                    <td class="text-center">
                                        {% if object.is_staff %}
                                            <i class="fa fa-check-circle"></i>
                                        {% else %}
                                            <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td class="text-center">
                                        {% if object.is_active %}
                                            <i class="fa fa-check-circle"></i>
                                        {% else %}
                                            <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td>{{ object.last_login }}</td>
                                    <td>
                                        <a {% if not object.is_active %} class="invisible" {% endif %}
                                                                         href="{% url 'admin_staff:user_delete' pk=object.id %}">
                                            <i class="fa fa-times-circle"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'adminapp:user_create' %}">
                        <button class="btn btn-success">Создать пользователя</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}