authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path, include
import basketapp.views as basket

app_name = 'basketapp'

urlpatterns = [
    path('', basket.index, name='index'),
    path('add/<int:pk>/', basket.add, name='add'),
    path('remove/<int:pk>)/', basket.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp.views import index, contacts

# import mainapp.views as mainapp - можно сразу все импортнуть


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    # path('contacts/', mainapp.contacts, name='contacts'), - если все импортировали, то подгружать так
    path('products/', include('productsapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

products/urls.py
from django.urls import path, include
# from .views import products
import products.views as products

urlpatterns = [
    # path('', products),
    path('', products.index),
]

productsapp/urls.py
from django.urls import path, include
# from .views import productsapp
import productsapp.views as products
from django.views.decorators.cache import cache_page

app_name = 'productsapp'

urlpatterns = [
    # path('', productsapp),
    path('', products.index, name='index'),
    path('<int:pk>/', products.index, name='category'),
    path('<int:pk>/page/<int:page>/', products.index, name='page'),
    path('product/<int:pk>/', cache_page(3600)(products.product), name='product'),
]

productsapp/models.py
from django.db import models


# Create your models here.
class ProductCategory (models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    create_at = models.DateTimeField(verbose_name='создано', auto_now_add=True)
    update_at = models.DateTimeField(verbose_name='обновлено', auto_now=True)
    is_active = models.BooleanField(verbose_name='активный', db_index=True, default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активный', db_index=True, default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

products/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'products/products.html')

productsapp/views.py
import random
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page


# cache functions
def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, \
                                              category__is_active=True).select_related('category')
            cache.set(key, products)
            # print('set cache')
        # else:
        #     print('from cache')
        return products
    else:
        return Product.objects.filter(is_active=True, \
                                      category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, \
                                              category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, \
                                      category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, \
                                              category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, \
                                      category__is_active=True).order_by('price')


# old functions
def get_hot_product():
    # products = Product.objects.filter(is_active=True, category__is_active=True)
    products = get_products()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True,
                                           category__is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


# кеширование контроллеров удобно так же производить в urls.py
@cache_page(60)
def index(request, pk=None, page=1):
    title = 'продукты'

    # links_menu = ProductCategory.objects.filter(is_active=True)
    links_menu = get_links_menu()

    if pk is not None:
        if pk == 0:
            category = {'pk': 0, 'name': 'все'}
            # products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price'). \
            #     select_related()
            products = get_products_orederd_by_price()
        else:
            # category = get_object_or_404(ProductCategory, pk=pk)
            category = get_category(pk)
            # products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True). \
            #     order_by('price')
            products = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }
        # return render(request, 'productsapp/products_list.html', content)

    else:
        hot_product = get_hot_product()
        same_products = get_same_products(hot_product)

        content = {
            'title': title,
            'links_menu': links_menu,
            'same_products': same_products,
            'hot_product': hot_product,
        }

    return render(request, 'productsapp/products.html', content)


def product(request, pk):
    title = 'продукт'

    content = {
        'title': title,
        # 'links_menu': ProductCategory.objects.all(),
        'links_menu': get_links_menu(),
        # 'product': get_object_or_404(Product, pk=pk),
        'product': get_product(pk),
    }

    return render(request, 'productsapp/product.html', content)

productsapp/templates/productsapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block mainmenu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_mainmenu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            <ul class="links-menu">
                <li><a href="{% url 'products:category' 0 %}"
                       class="{% if request.resolver_match.kwargs.pk|default:0 == 0 %}active{% endif %}">Все</a></li>
                {% for link in links_menu %}
                    <li><a href="{% url 'products:category' link.pk %}"
                           class="{% if request.resolver_match.kwargs.pk == link.pk %}active{% endif %}">{{ link.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>


        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{% static 'mainapp/img/controll.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'mainapp/img/controll1.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'mainapp/img/controll2.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>




    </div>

{% endblock %}

productsapp/templates/productsapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block mainmenu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_mainmenu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            <ul class="links-menu">
                <li><a href="{% url 'products:category' 0 %}"
                       class="{% if request.resolver_match.kwargs.pk|default:0 == 0 %}active{% endif %}">Все</a></li>
                {% for link in links_menu %}
                    <li><a href="{% url 'products:category' link.pk %}"
                           class="{% if request.resolver_match.kwargs.pk == link.pk %}active{% endif %}">{{ link.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        {% if not category %}
            <div class="details-products">
                <div class="details-slider">
                    <div class="slider-product">
                        <img src="{{ hot_product.image|media_folder_products }}">
                    </div>
                    <div class="slider-control">
                        <div class="block">
                            <a href="#"><img src="{% static 'mainapp/img/controll.jpg' %}" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="{% static 'mainapp/img/controll1.jpg' %}" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="{% static 'mainapp/img/controll2.jpg' %}" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="description">
                    <h3 class="big-bold">{{ hot_product.name }}</h3>
                    <h3 class="red">горячее предложение</h3>
                    <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                    <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                        заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </a>
                    <div class="description-text">
                        {{ hot_product.description }}
                    </div>
                </div>
            </div>
        {% endif %}

        {% if category %}
            <div class="related">
                <div class="title clearfix">
                    <h2>Категория "{{ category.name|title }}"</h2>
                </div>
                <div class="related-products clearfix">
                    <div class="paginator">
                        {% if products.has_previous %}
                            <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                                <
                            </a>
                        {% endif %}
                        <span class="current">
                            страница {{ products.number }} из {{ products.paginator.num_pages }}
                        </span>
                        {% if products.has_next %}
                            <a href="{% url 'products:page' category.pk products.next_page_number %}">
                                >
                            </a>
                        {% endif %}
                    </div>
                    {% for product in products %}
                        <div class="block">
                            <a href="{% url 'products:product' product.pk %}"><img
                                    src="{{ product.image|media_folder_products }}" alt="">
                                <div class="text">
                                    <img src="{% static 'mainapp/img/icon-hover.png' %}" alt="img">
                                    <h4>{{ product.name }}</h4>
                                    <p>{{ product.description }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if same_products %}
            <div class="related">
                <div class="title clearfix">
                    <h2>Похожие продукты</h2>
                </div>
                <div class="related-products clearfix">
                    {% for product in same_products %}
                        <div class="block">
                            <a href="{% url 'products:product' product.pk %}"><img src="{{ product.image|media_folder_products }}"
                                                                                   alt="">
                                <div class="text">
                                    <img src="{% static 'mainapp/img/icon-hover.png' %}" alt="img">
                                    <h4>{{ product.name }}</h4>
                                    <p>{{ product.description }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

    </div>

{% endblock %}