authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp.views import index, contacts

# import mainapp.views as mainapp - можно сразу все импортнуть


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    # path('contacts/', mainapp.contacts, name='contacts'), - если все импортировали, то подгружать так
    path('products/', include('productsapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('get/price/<int:pk>/', ordersapp.get_item_price, name='get_item_price'),
    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),

]

ordersapp/models.py
from django.db import models
from django.utils.functional import cached_property

from django.conf import settings
from productsapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', db_index=True, default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    # кешируем один и тот же запрос
    @cached_property
    def get_items_cached(self):
        return self.orderitems.select_related()

    def get_total_quantity(self):
        # items = self.orderitems.select_related()
        items = self.get_items_cached
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        # items = self.orderitems.select_related()
        items = self.get_items_cached
        return len(items)

    def get_total_cost(self):
        # items = self.orderitems.select_related()
        items = self.get_items_cached
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    # Вместо двух методов «get_total_quantity()» и «get_total_cost()»
    # при использовании тега with в шаблоне будет один запрос
    def get_summary(self):
        # items = self.orderitems.select_related()
        items = self.get_items_cached
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }


    # переопределяем метод, удаляющий объект, возвращаем на склад
    def delete(self):
        # возврат позиций на склад (тут кеш страшно ставить)
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        # деактивируем заказ, без настоящего удаления
        self.is_active = False
        self.save()


# описание в basketapp/models.py
class OrderItemQuerySet(models.QuerySet):

    def delete(self, *args, **kwargs):
        for object in self:
            object.product.quantity += object.quantity
            object.product.save()
        super(OrderItemQuerySet, self).delete(*args, **kwargs)

class OrderItem(models.Model):
    # перешли на сигналы
    # objects = OrderItemQuerySet.as_manager()

    order = models.ForeignKey(Order,
                              related_name="orderitems",
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

    # # перешли на сигналы в ordersapp/views.py
    # def delete(self):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super(self.__class__, self).delete()

ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem
from productsapp.models import Product


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        exclude = ()

    # Виртуальное поле, его нет в БД. Не сохраняется в БД (required) и задаем имя (label)
    price = forms.CharField(label='цена', required=False)

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        #Отфильтровать продукты только с положительным остатком на складе + сортировка
        self.fields['product'].queryset = Product.objects.filter(is_active=True, quantity__gte=1).\
            order_by('category', 'name').select_related()

ordersapp/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction
from django.db.models import F

from django.forms import inlineformset_factory
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm
from productsapp.models import Product

# приемник сигналов «receiver»
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete


# <имя класса>_list.html
class OrderList(ListView):
    model = Order

    extra_context = {'title': 'заказы/список'}

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

    # только залогиненые могут сюда попасть
    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(ListView, self).dispatch(*args, **kwargs)


# <имя класса>_form.html
class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')
    extra_context = {'title': 'заказ/создание'}

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        """
        Необходимо обеспечить создание элементов заказа одновременно с самим заказом. По сути, каждый элемент заказа 
        должен создаваться на отдельной форме, для этого нам потребуется набор форм Django FormSets, связанных с 
        родительским классом (в нашем случае это заказ «Order», а не простой, на базе класса «OrderItem»). В Django это
        класс «InlineFormSet» (формы на основе моделей). Для его создания воспользуемся методом 
        «inlineformset_factory()» из модуля «django.forms».
        Первый позиционный аргумент - родительский класс, второй - класс, на основе которого будет создаваться набор 
        форм класса, указанного в именованном аргументе «form=OrderItemForm». Аргумент «extra» позволяет задать 
        количество новых форм в наборе
        """
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                basket_items.delete()
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


# <имя класса>_form.html
class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')
    extra_context = {'title': 'заказ/редактирование'}

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            # для оптимизации прописываем применение select_related() в запрос
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance=self.object, queryset=queryset)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            # form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


# <имя класса>_confirm_delete.html
class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')


# <имя класса>_detail.html
class OrderRead(DetailView):
    model = Order
    extra_context = {'title': 'заказ/просмотр'}


# изменения статуса заказа
def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('ordersapp:orders_list'))


# запрос цены для позиции товара в заказе
def get_item_price(request, pk):
    if request.is_ajax():
        product = get_object_or_404(Product, pk=pk)
        return JsonResponse({'price': product.price})
    return JsonResponse({'price': 0})


# СИГНАЛЫ
# функции при сохранении и удалении объектов моделей «Basket» и «OrderItem» через сигналы (декоратор @receiver)
# «sender» - класс отправителя;
# «update_fields» - имена обновляемых полей;
# «instance» - сам обновляемый объект
@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    # непонятно зачем вообще нужен это if. всегда прилетает None!
    if update_fields is 'quantity' or 'product':
        if instance.pk:
            # тут падает при loaddata
            if sender.get_item(instance.pk) is not None:
                instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
        else:
            # instance.product.quantity -= instance.quantity
            instance.product.quantity = F('quantity') - instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    # instance.product.quantity += instance.quantity
    instance.product.quantity = F('quantity') + instance.quantity
    instance.product.save()
    print('delete')

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
{% endblock %}

{% block mainmenu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_mainmenu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
       </button>
   </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
{% endblock %}

{% block mainmenu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_mainmenu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <img src="{{ item.product.image|media_folder_products }}"
                    alt="{{ item.product.short_desc }}">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load cache %}

{% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
{% endblock %}

{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'ordersapp/js/jquery.formset.js' %}"></script>
    <script src="{% static 'ordersapp/js/orders_scripts.js' %}"></script>
{% endblock %}

{% block mainmenu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_mainmenu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table table-striped">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
                               <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                   {{ field.label|capfirst }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}

                               {% if field.name != 'price' %}
                                {% if field.name == 'product' %}
                                   {% cache 360 orderitemform_product field.value %}
                                       {{ field }}
                                   {% endcache %}
                                {% else %}
                                   {{ field }}
                                {% endif %}
                               {% else %}
                                   {% if field.value %}
                                       <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                        {{ field.value }}
                                       </span> <i class="fas fa-ruble-sign"></i>
                                   {% endif %}
                               {% endif %}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
           {% include 'ordersapp/includes/inc_order_actions.html' %}
       </form>
   </div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
{% endblock %}

{% block mainmenu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_mainmenu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}

   <div class="h2 text-center head">
       Ваши заказы,
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
           <th>Действия</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           посмотреть
                       </a>
                      {% if item.status == 'FM' %}
                         &nbsp;<a href="{% url 'ordersapp:order_update' item.pk %}">
                           редактировать
                         </a>
                         &nbsp;<a href="{% url 'ordersapp:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
   <button class="btn btn-default btn-round">
       <a href="{% url 'index' %}">
           на главную
       </a>
   </button>
   <button class="btn btn-default btn-round">
       <a href="{% url 'ordersapp:order_create' %}">
           новый
       </a>
   </button>
{% endblock %}